#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'ghc', :path => 'site-cookbooks'
cookbook 'imagemagick', :path => 'site-cookbooks'
cookbook 'joelteon', :path => 'site-cookbooks'
cookbook 'postgres', :path => 'site-cookbooks'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
